/**:
  ros__parameters:

    cam_topic: gripper_rgbd/image_raw

    use_thermal: false

    use_qr: true

    use_april: true
    
    object_detection_topic: victim_crate/perceptions

    use_motion: false

    motion_topic: motion_detection
