<?xml version='1.0' encoding='UTF-8'?>
<package format="3">
  <name>hector_tag_detection</name>
  <version>1.0.0</version>
  <description>hector_tag_detection searches for QR codes in images using the</description>
  <maintainer email="finn.winter@stud.tu-darmstadt.de">Finn Winter</maintainer>
  <license>LGPL</license>
  <url type="website">http://ros.org/wiki/hector_tag_detection</url>
  <author>Johannes Meyer</author>
  <!-- <url type="bugtracker"></url> -->
  <author email="kohlbrecher@sim.tu-darmstadt.de">Stefan Kohlbrecher</author>

  <!-- Dependencies which this package needs to build itself. -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>apriltag</depend>
  <depend>cv_bridge</depend>
  <depend>hector_ros2_utils</depend>
  <depend>image_transport</depend>
  <!-- Dependencies needed to compile this package. -->
  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>vision_msgs</depend>
  <depend>zbar_ros</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
