/**:
  ros__parameters:

    cam_topic: gripper_rgbd/image_raw

    use_thermal: false

    use_qr: true

    object_detection_topic: semantic_detection_node/object_detections

    use_motion: true

    motion_topic: motion_detection
