<?xml version="1.0"?>
<package format="2">
  <name>hector_qrcode_detection</name>
  <version>1.0.0</version>
  <description>hector_qrcode_detection searches for QR codes in images using the</description>
  <maintainer email="kohlbrecher@sim.tu-darmstadt.de">Stefan Kohlbrecher</maintainer>

  <license>LGPL</license>

  <url type="website">http://ros.org/wiki/hector_qrcode_detection</url>
  <!-- <url type="bugtracker"></url> -->

  <author>Johannes Meyer</author>

  <!-- Dependencies which this package needs to build itself. -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dependencies needed to compile this package. -->
  <depend>rclcpp</depend>
  <depend>image_transport</depend>
  <depend>cv_bridge</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>zbar</depend>
  <depend>vision_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
